import { Schema, model, type Document, Types } from "mongoose";
import type { PaymentSettings, PaymentStatus } from "../../domain/entities/payment.entity";

export interface PaymentSettingsDocument extends Document, Omit<PaymentSettings, "id" | "createdAt" | "updatedAt"> { createdAt: Date; updatedAt: Date; }
export interface ReservationPaymentDocument extends Document { reservationId: Types.ObjectId; method: "VIETQR"; amount: number; transactionReference: string; transferContent: string; status: PaymentStatus; bankCode: string; bankName: string; accountNumber: string; accountName: string; qrTemplate: string; qrImageUrl: string; customerMarkedPaidAt?: Date; confirmedBy?: Types.ObjectId; confirmedAt?: Date; adminNote?: string; createdAt: Date; updatedAt: Date; }

const settingsSchema = new Schema<PaymentSettingsDocument>({ provider: { type: String, enum: ["VIETQR"], default: "VIETQR" }, enabled: { type: Boolean, default: false }, bankCode: String, bankName: String, accountNumber: String, accountName: String, qrTemplate: { type: String, default: "compact2" }, paymentInstructions: { type: String, default: "" }, updatedBy: { type: String, required: true } }, { timestamps: true });
const paymentSchema = new Schema<ReservationPaymentDocument>({ reservationId: { type: Schema.Types.ObjectId, ref: "Reservation", required: true, unique: true }, method: { type: String, enum: ["VIETQR"], required: true }, amount: { type: Number, required: true }, transactionReference: { type: String, required: true, unique: true }, transferContent: { type: String, required: true }, status: { type: String, enum: ["PENDING", "PENDING_APPROVAL", "CONFIRMED", "REJECTED"], required: true }, bankCode: String, bankName: String, accountNumber: String, accountName: String, qrTemplate: String, qrImageUrl: String, customerMarkedPaidAt: Date, confirmedBy: { type: Schema.Types.ObjectId, ref: "User" }, confirmedAt: Date, adminNote: String }, { timestamps: true });
export const PaymentSettingsModel = model<PaymentSettingsDocument>("PaymentSettings", settingsSchema);
export const ReservationPaymentModel = model<ReservationPaymentDocument>("ReservationPayment", paymentSchema);
