import type { NextFunction, Request, Response } from "express";
import { HttpResponse } from "@/core/http/response";
import { BadRequestError } from "@/core/errors";
import type { CreateReservationUseCase, GetOccupiedSeatsUseCase, GetMyReservationsUseCase, GetAdminReservationsUseCase, GetReservationPaymentUseCase, ConfirmCustomerPaymentUseCase, ApproveManualPaymentUseCase, RejectManualPaymentUseCase, UpdateReservationStatusUseCase, DeleteReservationUseCase, GetReservationConfigUseCase } from "../../application/use-cases/reservation.use-cases";

export class ReservationController {
  constructor(private readonly create: CreateReservationUseCase, private readonly occupied: GetOccupiedSeatsUseCase, private readonly mine: GetMyReservationsUseCase, private readonly adminList: GetAdminReservationsUseCase, private readonly payment: GetReservationPaymentUseCase, private readonly customerConfirm: ConfirmCustomerPaymentUseCase, private readonly adminApprove: ApproveManualPaymentUseCase, private readonly adminReject: RejectManualPaymentUseCase, private readonly updateStatus: UpdateReservationStatusUseCase, private readonly remove: DeleteReservationUseCase, private readonly config: GetReservationConfigUseCase) {}
  configHandler = (_req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, this.config.execute(), "Reservation config retrieved successfully"); } catch (e) { next(e); } };
  createHandler = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.created(res, await this.create.execute({ ...req.body, userId: req.user!.id }), "Reservation created successfully!"); } catch (e) { next(e); } };
  occupiedHandler = async (req: Request, res: Response, next: NextFunction) => { try { const { date, session, slotId } = req.query; if (!date || !session || !slotId) throw new BadRequestError("date, session, and slotId are required"); return HttpResponse.success(res, await this.occupied.execute(String(date), String(session), String(slotId)), "Occupied seats retrieved successfully"); } catch (e) { next(e); } };
  mineHandler = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.mine.execute(req.user!.id), "Your reservations retrieved successfully"); } catch (e) { next(e); } };
  getAll = async (_req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.adminList.execute(), "Reservations retrieved successfully"); } catch (e) { next(e); } };
  getById = async (req: Request, res: Response, next: NextFunction) => { try { const result = await this.payment.execute(String(req.params.id), req.user!.id, true); return HttpResponse.success(res, result.reservation, "Reservation retrieved successfully"); } catch (e) { next(e); } };
  getPayment = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.payment.execute(String(req.params.id), req.user!.id, req.user!.role === "admin"), "Payment retrieved successfully"); } catch (e) { next(e); } };
  confirmPayment = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.customerConfirm.execute(String(req.params.id), req.user!.id), "Payment submitted for approval"); } catch (e) { next(e); } };
  approvePayment = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.adminApprove.execute(String(req.params.id), req.user!.id, req.body.receivedAmount, req.body.note), "Payment approved successfully"); } catch (e) { next(e); } };
  rejectPayment = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.adminReject.execute(String(req.params.id), req.body.note), "Payment rejected successfully"); } catch (e) { next(e); } };
  update = async (req: Request, res: Response, next: NextFunction) => { try { return HttpResponse.success(res, await this.updateStatus.execute(String(req.params.id), req.body.status), "Reservation status updated successfully"); } catch (e) { next(e); } };
  delete = async (req: Request, res: Response, next: NextFunction) => { try { await this.remove.execute(String(req.params.id)); return HttpResponse.success(res, null, "Reservation deleted successfully"); } catch (e) { next(e); } };
}
